[workspace]
members = ["crates/bulkmail", "crates/mempooloracle"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Tyler Smith <mail@tcry.pt>"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
alloy = { version = "1.7.3", default-features = false, features = [
    "std",
    "provider-ws",
    "rpc-types",
    "signer-local",
    "k256",
] }
alloy-node-bindings = "1.7.3"
async-trait = "0.1.89"
ethereum-types = "0.16.0"
futures = "0.3.32"
log = "0.4.29"
mockall = "0.14.0"
mempooloracle = { path = "crates/mempooloracle", version = "0.1.0" }
parking_lot = "0.12.1"
rand = "0.10.0"
secp256k1 = "0.31.1"
serde = { version = "1.0.228", features = ["derive"] }
simple_logger = "5.2.0"
solana-client = { version = "2.2", default-features = false }
solana-sdk = { version = "2.2", default-features = false, features = ["full"] }
solana-transaction-status = { version = "2.2", default-features = false }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["rt", "rt-multi-thread", "sync", "time", "macros"] }
tracing = "0.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.ci]
inherits = "dev"
debug = false
incremental = false
debug-assertions = true
overflow-checks = true
